# .github/workflows/test.yml
name: Test WebPrintBypass

on: [push]

jobs:
  test-puppeteer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd puppeteer && npm install
      - run: cd puppeteer && node index.js

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: cd python && pip install playwright && playwright install chromium
      - run: cd python && python main.py